### ISSUE TITLE
NullPointer al finalizar ejecución, probablemente de la GUI

### ISSUE THREAD

**Issue by Jorjatorz** [hecoding/Pac-Man#38]
Otput de la consola de Eclipse:

```
mar 13, 2017 11:39:35 AM jeco.core.algorithm.moge.GrammaticalEvolution execute
INFORMACIÓN: @ # Gen. 100, objective values:
Error: unknown selection clause
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at parser.nodes.NicerTree.pretty(NicerTree.java:33)
	at view.gui.swing.GeneralController.getBestProgramPretty(GeneralController.java:223)
	at view.gui.swing.CenterPanel$4.run(CenterPanel.java:196)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: 

mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Fitness =  [5.0]
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Average points = 5.0
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Phenotype = (if(_getDistanceToClosestEdibleGhost_LE_50_){_getDirectionTowardsClosestPill_}_else{_if(_getClosestNonEdibleGhostDistanceToClosestJunctionLeft_LE_10_){_getDirectionTowardsClosestPill_}_else{_if(_getDistanceToClosestNonEdibleGhost_LE_10_){_getDirectionTowardsClosestPowerPill_}_}_})
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: 

mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Fitness =  [5.0]
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Average points = 5.0
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Phenotype = (if(_getDistanceToClosestEdibleGhost_LT_50_){_getDirectionTowardsClosestPill_}_else{_if(_getClosestNonEdibleGhostDistanceToClosestJunctionLeft_LE_15_){_getDirectionTowardsClosestPill_}_else{_if(_getDistanceToClosestNonEdibleGhost_LE_10_){_getDirectionTowardsClosestPowerPill_}_}_})
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: 

mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Fitness =  [5.0]
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Average points = 5.0
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Phenotype = (if(_getDistanceToClosestEdibleGhost_LT_50_){_getDirectionTowardsClosestPill_}_else{_if(_getClosestNonEdibleGhostDistanceToClosestJunctionLeft_LE_15_){_getDirectionTowardsClosestPill_}_else{_if(_getDistanceToClosestNonEdibleGhost_LE_10_){_getDirectionTowardsClosestPowerPill_}_}_})
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: 

mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Fitness =  [5.0]
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Average points = 5.0
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Phenotype = (if(_getDistanceToClosestEdibleGhost_LT_50_){_getDirectionTowardsClosestPill_}_else{_if(_getClosestNonEdibleGhostDistanceToClosestJunctionLeft_LE_15_){_getDirectionTowardsClosestPill_}_else{_if(_getDistanceToClosestNonEdibleGhost_LE_10_){_getDirectionTowardsClosestPowerPill_}_}_})
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: 

mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Fitness =  [5.0]
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Average points = 5.0
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Phenotype = (if(_getDistanceToClosestEdibleGhost_LT_50_){_getDirectionTowardsClosestPill_}_else{_if(_getClosestNonEdibleGhostDistanceToClosestJunctionLeft_LT_10_){_getDirectionTowardsClosestPill_}_else{_if(_getDistanceToClosestNonEdibleGhost_LE_10_){_getDirectionTowardsClosestPowerPill_}_}_})
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: 

mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Fitness =  [5.0]
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Average points = 5.0
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Phenotype = (if(_getDistanceToClosestEdibleGhost_LT_50_){_getDirectionTowardsClosestPill_}_else{_if(_getClosestNonEdibleGhostDistanceToClosestJunctionLeft_LT_10_){_getDirectionTowardsClosestPill_}_else{_if(_getDistanceToClosestNonEdibleGhost_LE_10_){_getDirectionTowardsClosestPowerPill_}_}_})
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: 

mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Fitness =  [5.0]
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Average points = 5.0
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Phenotype = (if(_getDistanceToClosestEdibleGhost_LT_50_){_getDirectionTowardsClosestPill_}_else{_if(_getClosestNonEdibleGhostDistanceToClosestJunctionLeft_LE_10_){_getDirectionTowardsClosestPill_}_else{_if(_getDistanceToClosestNonEdibleGhost_LE_10_){_getDirectionTowardsClosestPowerPill_}_}_})
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: 

mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Fitness =  [5.0]
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Average points = 5.0
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Phenotype = (if(_getDistanceToClosestEdibleGhost_LE_50_){_getDirectionTowardsClosestPill_}_else{_if(_getClosestNonEdibleGhostDistanceToClosestJunctionLeft_LE_10_){_getDirectionTowardsClosestPill_}_else{_if(_getDistanceToClosestNonEdibleGhost_LT_10_){_getDirectionTowardsClosestPowerPill_}_}_})
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: 

mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Fitness =  [5.0]
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Average points = 5.0
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Phenotype = (if(_getDistanceToClosestEdibleGhost_LT_50_){_getDirectionTowardsClosestPill_}_else{_if(_getClosestNonEdibleGhostDistanceToClosestJunctionLeft_LE_15_){_getDirectionTowardsClosestPill_}_else{_if(_getDistanceToClosestNonEdibleGhost_LE_10_){_getDirectionTowardsClosestPowerPill_}_}_})
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: 

mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Fitness =  [5.0]
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Average points = 5.0
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Phenotype = (if(_getDistanceToClosestEdibleGhost_LE_40_){_getDirectionTowardsClosestPill_}_else{_if(_getClosestNonEdibleGhostDistanceToClosestJunctionLeft_LE_10_){_getDirectionTowardsClosestPill_}_else{_if(_getDistanceToClosestNonEdibleGhost_LE_10_){_getDirectionTowardsClosestPowerPill_}_}_})
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: 

mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Fitness =  [5.0]
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Average points = 5.0
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Phenotype = (if(_getClosestEdibleGhostDistanceToClosestJunctionUp_LE_40_){_getDirectionTowardsClosestPowerPill_}_else{_if(_getClosestNonEdibleGhostDistanceToClosestJunctionLeft_LE_20_){_getDirectionTowardsClosestPill_}_else{_if(_getDistanceToClosestNonEdibleGhost_LE_10_){_getDirectionTowardsClosestPowerPill_}_}_})
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: 

mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Fitness =  [5.0]
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Average points = 5.0
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Phenotype = (if(_getDistanceToClosestEdibleGhost_LT_50_){_getDirectionTowardsClosestPill_}_else{_if(_getClosestNonEdibleGhostDistanceToClosestJunctionLeft_LE_15_){_getDirectionTowardsClosestPill_}_else{_if(_getDistanceToClosestNonEdibleGhost_LE_10_){_getDirectionTowardsClosestPowerPill_}_}_})
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: 

mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Fitness =  [5.0]
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Average points = 5.0
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Phenotype = (if(_getClosestEdibleGhostDistanceToClosestJunctionUp_LE_40_){_getDirectionTowardsClosestPowerPill_}_else{_if(_getClosestNonEdibleGhostDistanceToClosestJunctionLeft_LE_20_){_getDirectionTowardsClosestPill_}_else{_if(_getDistanceToClosestNonEdibleGhost_LE_10_){_getDirectionTowardsClosestPowerPill_}_}_})
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: 

mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Fitness =  [5.0]
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Average points = 5.0
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Phenotype = (if(_getDistanceToClosestEdibleGhost_LE_50_){_getDirectionTowardsClosestPill_}_else{_if(_getClosestNonEdibleGhostDistanceToClosestJunctionLeft_LE_10_){_getDirectionTowardsClosestPill_}_else{_if(_getDistanceToClosestNonEdibleGhost_LE_10_){_getDirectionTowardsClosestPowerPill_}_}_})
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: 

mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Fitness =  [5.0]
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Average points = 5.0
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Phenotype = (if(_getDistanceToClosestEdibleGhost_LT_50_){_getDirectionTowardsClosestPill_}_else{_if(_getClosestNonEdibleGhostDistanceToClosestJunctionLeft_LE_10_){_getDirectionTowardsClosestPill_}_else{_if(_getDistanceToClosestNonEdibleGhost_LE_10_){_getDirectionTowardsClosestPowerPill_}_}_})
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: 

mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Fitness =  [5.0]
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Average points = 5.0
mar 13, 2017 11:39:37 AM view.gui.swing.ProgramWorker exec
INFORMACIÓN: Phenotype = (if(_getDistanceToClosestEdibleGhost_LT_50_){_getDirectionTowardsClosestPill_}_else{_if(_getClosestNonEdibleGhostDistanceToClosestJunctionLeft_LE_10_){_getDirectionTowardsClosestPill_}_else{_if(_getDistanceToClosestNonEdibleGhost_LE_10_){_getDirectionTowardsClosestPowerPill_}_}_})
Updated log under: logs/Registro.csv

```

**Comment by hecoding** [comment]
Acabo de verlo lol
Gracias por el stacktrace, parece que peta al pasar el árbol a código para mostrarlo en la GUI. Tendremos que ver si alguno de estos fenotipos es el que peta.
@J-888
